//var day1Solver = new AdventOfCode2024.Day1.Solver(sample: false);
//Console.Write("Day 1 Part 1: ");
//Console.WriteLine(day1Solver.Part1());
//Console.Write("Day 1 Part 2: ");
//Console.WriteLine(day1Solver.Part2());
//var day2Solver = new AdventOfCode2024.Day2.Solver(sample: false);
//Console.Write("Day 2 Part 1: ");
//Console.WriteLine(day2Solver.Part1());
//Console.Write("Day 2 Part 2: ");
//Console.WriteLine(day2Solver.Part2());
//var day3Solver = new AdventOfCode2024.Day3.Solver(sample: false);
//Console.Write("Day 3 Part 1: ");
//Console.WriteLine(day3Solver.Part1());
//Console.Write("Day 3 Part 2: ");
//Console.WriteLine(day3Solver.Part2());
//var day4Solver = new AdventOfCode2024.Day4.Solver(sample: false);
//Console.Write("Day 4 Part 1: ");
//Console.WriteLine(day4Solver.Part1());
//Console.Write("Day 4 Part 2: ");
//Console.WriteLine(day4Solver.Part2());
//var day5Solver = new AdventOfCode2024.Day5.Solver(sample: false);
//Console.Write("Day 5 Part 1: ");
//Console.WriteLine(day5Solver.Part1());
//Console.Write("Day 5 Part 2: ");
//Console.WriteLine(day5Solver.Part2());
//var day6Solver = new AdventOfCode2024.Day6.Solver(sample: false);
//Console.Write("Day 6 Part 1: ");
//Console.WriteLine(day6Solver.Part1());
//Console.Write("Day 6 Part 2: ");
//Console.WriteLine(day6Solver.Part2());
var day7Solver = new AdventOfCode2024.Day7.Solver(sample: false);
Console.Write("Day 7 Part 1: ");
Console.WriteLine(day7Solver.Solve(false));
Console.Write("Day 7 Part 2: ");
Console.WriteLine(day7Solver.Solve(true));

